services:
  frontend:
    build: ./cocatalk-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./cocatalk-frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=cocatalk
      - POSTGRES_USER=jux
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  node_modules:
  pgdata: